
# Regression Models with Keras

## Introduction

As we've studied, despite the popularity of more powerful libraries such as PyToch and TensorFlow, they are not easy to use and have a steep learning curve. So, for people who are just starting to learn deep learning, there is no better library to use other than the Keras library. 

Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development. As you will see in this exercise and the other exercises in this course, building a very complex deep learning network can be achieved with Keras with only few lines of code. You will appreciate Keras even more, once you learn how to build deep models using PyTorch and TensorFlow in the other courses.

So, in this exercise, you will learn how to use the Keras library to build a regression model.

## Objectives for this Notebook    
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network

<h2>Table of Contents</h2>


<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 4>
1. <a href="#Download-and-Clean-the-Data-Set">Download and Clean the Data Set</a><br>
2. <a href="#Import-Keras-Packages">Import Keras Packages</a><br>
3. <a href="#Build-a-Neural-Network">Build a Neural Network</a><br>
4. <a href="#Train-and-Test-the-Network">Train and Test the Network</a><br>  

</font>
</div>

Let's start by importing the <em>pandas</em> and the Numpy libraries.

#### To use Keras, you will also need to install a backend framework – such as TensorFlow.

If you install TensorFlow 2.16 or above, it will install Keras by default.

We are using the CPU version of tensorflow since we are dealing with smaller datasets. 
You may install the GPU version of tensorflow on your machine to accelarate the processing of larger datasets

#### Suppress the tensorflow warning messages
We use the following code to  suppress the warning messages due to use of CPU architechture for tensoflow.

You may want to **comment out** these lines if you are using the GPU architechture

In [1]:
import os
## os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

We will be playing around with the same dataset that we used in the videos.

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

* Cement
* Blast furnace slag
* Fly ash
* Water
* Superplasticizer
* Coarse aggregate
* Fine aggregate

## Download and Clean the Data Set

Let's download the data and read it into a <em>pandas</em> dataframe.

In [4]:
concrete_data = pd.read_csv("4.1_concrete_data.csv")
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

#### Let's check how many data points we have

In [5]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

Let's check the dataset for any missing values.

In [6]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [7]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [8]:
concrete_data_columns = concrete_data.columns

In [9]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.

In [10]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [11]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [12]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [13]:
n_cols = predictors_norm.shape[1] # number of predictors

<a id="item1"></a>

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.

In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [15]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

## Train and Test the Network

Let's call the function now to create our model.

In [16]:
# build the model
model = regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [17]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 38ms/step - loss: 1690.2825 - val_loss: 1167.4550
Epoch 2/100
23/23 - 0s - 5ms/step - loss: 1571.4171 - val_loss: 1056.7606
Epoch 3/100
23/23 - 0s - 6ms/step - loss: 1396.4410 - val_loss: 895.1083
Epoch 4/100
23/23 - 0s - 7ms/step - loss: 1129.2157 - val_loss: 672.8956
Epoch 5/100
23/23 - 0s - 6ms/step - loss: 786.7845 - val_loss: 431.0847
Epoch 6/100
23/23 - 0s - 6ms/step - loss: 463.8715 - val_loss: 249.5610
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 290.7965 - val_loss: 174.5090
Epoch 8/100
23/23 - 0s - 5ms/step - loss: 236.6886 - val_loss: 158.1618
Epoch 9/100
23/23 - 0s - 6ms/step - loss: 219.0580 - val_loss: 157.2203
Epoch 10/100
23/23 - 0s - 4ms/step - loss: 205.6679 - val_loss: 154.7196
Epoch 11/100
23/23 - 0s - 4ms/step - loss: 195.8127 - val_loss: 152.0379
Epoch 12/100
23/23 - 0s - 5ms/step - loss: 188.5728 - val_loss: 151.1664
Epoch 13/100
23/23 - 0s - 4ms/step - loss: 182.9736 - val_loss: 148.6494
Epoch 14/100
23/23 - 0s - 5ms/step - loss: 177.7712 - val_loss: 150.9338
Epoch 15/100
23/23 - 0s - 5ms/step - loss: 173.1947 - val_loss: 147.8797
Epoch 16/100
23/23 - 0s - 6ms/step - loss: 169.0386 - val_loss: 146.5872
Epoch 17/100
23/23 - 0s - 6ms/step - loss: 166.1668 - val_loss: 146.3434
Epoch 18/100
23/23 - 0s - 5ms/step - loss: 162.7010 - val_loss: 145.3686
Epoch 19/100
23/23 - 0s - 5ms/step - loss: 159.5384 - val_loss: 146.2398
Epoch 20/100
23/23 - 0s - 5ms/step - loss: 157.2431 - val_loss: 142.9906
Epoch 21/100
23/23 - 0s - 5ms/step - loss: 154.7536 - val_loss: 145.1401
Epoch 22/100
23/23 - 0s - 5ms/step - loss: 152.8427 - val_loss: 146.2056
Epoch 23/100
23/23 - 0s - 5ms/step - loss: 151.1386 - val_loss: 145.3531
Epoch 24/100
23/23 - 0s - 5ms/step - loss: 148.8728 - val_loss: 146.9125
Epoch 25/100
23/23 - 0s - 5ms/step - loss: 147.3851 - val_loss: 149.0926
Epoch 26/100
23/23 - 0s - 5ms/step - loss: 145.2450 - val_loss: 149.7061
Epoch 27/100
23/23 - 0s - 4ms/step - loss: 144.8193 - val_loss: 148.3219
Epoch 28/100
23/23 - 0s - 7ms/step - loss: 142.5541 - val_loss: 151.4445
Epoch 29/100
23/23 - 0s - 5ms/step - loss: 140.8946 - val_loss: 150.6735
Epoch 30/100
23/23 - 0s - 5ms/step - loss: 139.3816 - val_loss: 154.2338
Epoch 31/100
23/23 - 0s - 5ms/step - loss: 137.7177 - val_loss: 152.0562
Epoch 32/100
23/23 - 0s - 7ms/step - loss: 136.8246 - val_loss: 158.0152
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 135.4637 - val_loss: 152.8955
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 133.4410 - val_loss: 156.2346
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 132.0762 - val_loss: 156.2682
Epoch 36/100
23/23 - 0s - 5ms/step - loss: 131.6901 - val_loss: 158.4508
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 129.6992 - val_loss: 160.6154
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 127.7600 - val_loss: 160.7715
Epoch 39/100
23/23 - 0s - 7ms/step - loss: 126.2755 - val_loss: 158.8044
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 124.2927 - val_loss: 160.2757
Epoch 41/100
23/23 - 0s - 5ms/step - loss: 122.8737 - val_loss: 163.5539
Epoch 42/100
23/23 - 0s - 5ms/step - loss: 121.1079 - val_loss: 162.9639
Epoch 43/100
23/23 - 0s - 6ms/step - loss: 119.4084 - val_loss: 163.9661
Epoch 44/100
23/23 - 0s - 6ms/step - loss: 117.1400 - val_loss: 164.0368
Epoch 45/100
23/23 - 0s - 6ms/step - loss: 115.0956 - val_loss: 164.5853
Epoch 46/100
23/23 - 0s - 5ms/step - loss: 113.0276 - val_loss: 168.5049
Epoch 47/100
23/23 - 0s - 6ms/step - loss: 111.6032 - val_loss: 167.8906
Epoch 48/100
23/23 - 0s - 5ms/step - loss: 108.1515 - val_loss: 163.9311
Epoch 49/100
23/23 - 0s - 5ms/step - loss: 105.1473 - val_loss: 166.0188
Epoch 50/100
23/23 - 0s - 6ms/step - loss: 102.7034 - val_loss: 160.7777
Epoch 51/100
23/23 - 0s - 6ms/step - loss: 99.7184 - val_loss: 162.1345
Epoch 52/100
23/23 - 0s - 5ms/step - loss: 96.3817 - val_loss: 159.0455
Epoch 53/100
23/23 - 0s - 4ms/step - loss: 93.5096 - val_loss: 168.0183
Epoch 54/100
23/23 - 0s - 4ms/step - loss: 90.4013 - val_loss: 155.3223
Epoch 55/100
23/23 - 0s - 5ms/step - loss: 86.8819 - val_loss: 161.8249
Epoch 56/100
23/23 - 0s - 5ms/step - loss: 84.1229 - val_loss: 151.8671
Epoch 57/100
23/23 - 0s - 4ms/step - loss: 81.4717 - val_loss: 162.2275
Epoch 58/100
23/23 - 0s - 5ms/step - loss: 78.7745 - val_loss: 151.6429
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 76.1830 - val_loss: 156.7488
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 73.7675 - val_loss: 156.5363
Epoch 61/100
23/23 - 0s - 5ms/step - loss: 71.2506 - val_loss: 150.1069
Epoch 62/100
23/23 - 0s - 7ms/step - loss: 69.0083 - val_loss: 153.4048
Epoch 63/100
23/23 - 0s - 7ms/step - loss: 67.0947 - val_loss: 155.1791
Epoch 64/100
23/23 - 0s - 7ms/step - loss: 64.9334 - val_loss: 147.5391
Epoch 65/100
23/23 - 0s - 4ms/step - loss: 63.1241 - val_loss: 147.6414
Epoch 66/100
23/23 - 0s - 5ms/step - loss: 61.1612 - val_loss: 144.6891
Epoch 67/100
23/23 - 0s - 5ms/step - loss: 59.0831 - val_loss: 151.4111
Epoch 68/100
23/23 - 0s - 6ms/step - loss: 57.9485 - val_loss: 151.1731
Epoch 69/100
23/23 - 0s - 6ms/step - loss: 55.4315 - val_loss: 134.5796
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 54.3125 - val_loss: 151.7485
Epoch 71/100
23/23 - 0s - 5ms/step - loss: 52.4860 - val_loss: 141.6938
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 50.6040 - val_loss: 151.7401
Epoch 73/100
23/23 - 0s - 5ms/step - loss: 49.8531 - val_loss: 133.6553
Epoch 74/100
23/23 - 0s - 6ms/step - loss: 48.6058 - val_loss: 149.2039
Epoch 75/100
23/23 - 0s - 6ms/step - loss: 47.1279 - val_loss: 136.8885
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 46.4314 - val_loss: 134.9033
Epoch 77/100
23/23 - 0s - 5ms/step - loss: 45.1452 - val_loss: 145.6249
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 44.1452 - val_loss: 141.5630
Epoch 79/100
23/23 - 0s - 5ms/step - loss: 42.9696 - val_loss: 144.0219
Epoch 80/100
23/23 - 0s - 6ms/step - loss: 42.6252 - val_loss: 135.3607
Epoch 81/100
23/23 - 0s - 4ms/step - loss: 42.1154 - val_loss: 135.5206
Epoch 82/100
23/23 - 0s - 4ms/step - loss: 41.3810 - val_loss: 141.6934
Epoch 83/100
23/23 - 0s - 4ms/step - loss: 40.2175 - val_loss: 144.8038
Epoch 84/100
23/23 - 0s - 5ms/step - loss: 39.2662 - val_loss: 138.4639
Epoch 85/100
23/23 - 0s - 4ms/step - loss: 38.7538 - val_loss: 139.6537
Epoch 86/100
23/23 - 0s - 5ms/step - loss: 38.6441 - val_loss: 132.9312
Epoch 87/100
23/23 - 0s - 6ms/step - loss: 37.3839 - val_loss: 150.0561
Epoch 88/100
23/23 - 0s - 5ms/step - loss: 37.1407 - val_loss: 147.6645
Epoch 89/100
23/23 - 0s - 5ms/step - loss: 36.9002 - val_loss: 138.6949
Epoch 90/100
23/23 - 0s - 6ms/step - loss: 36.4839 - val_loss: 133.7988
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 36.0321 - val_loss: 146.0869
Epoch 92/100
23/23 - 0s - 5ms/step - loss: 34.7326 - val_loss: 143.9306
Epoch 93/100
23/23 - 0s - 4ms/step - loss: 34.3671 - val_loss: 151.5533
Epoch 94/100
23/23 - 0s - 4ms/step - loss: 34.7435 - val_loss: 148.3170
Epoch 95/100
23/23 - 0s - 5ms/step - loss: 33.5717 - val_loss: 142.2381
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 33.0681 - val_loss: 139.8646
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 32.6191 - val_loss: 153.6953
Epoch 98/100
23/23 - 0s - 5ms/step - loss: 32.4356 - val_loss: 138.6050
Epoch 99/100
23/23 - 0s - 5ms/step - loss: 32.1955 - val_loss: 142.9160
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 31.3765 - val_loss: 146.2112

<strong>You can refer to this [link](https://keras.io/models/sequential/) to learn about other functions that you can use for prediction or evaluation.</strong>

Feel free to vary the following and note what impact each change has on the model's performance:

1. Increase or decreate number of neurons in hidden layers
2. Add more hidden layers
3. Increase number of epochs

<h3>Practice Exercise 1</h3>

Now using the same dateset,try to recreate regression model featuring five hidden layers, each with 50 nodes and ReLU activation functions, a single output layer, optimized using the Adam optimizer.

In [18]:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [19]:
# build the model
model = regression_model()

In [20]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 55ms/step - loss: 1630.6198 - val_loss: 1044.0852
Epoch 2/100
23/23 - 0s - 6ms/step - loss: 975.0953 - val_loss: 198.9477
Epoch 3/100
23/23 - 0s - 5ms/step - loss: 295.1621 - val_loss: 196.3866
Epoch 4/100
23/23 - 0s - 5ms/step - loss: 224.6670 - val_loss: 212.8683
Epoch 5/100
23/23 - 0s - 5ms/step - loss: 206.0564 - val_loss: 182.9387
Epoch 6/100
23/23 - 0s - 5ms/step - loss: 185.5961 - val_loss: 182.1656
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 174.5749 - val_loss: 190.7250
Epoch 8/100
23/23 - 0s - 5ms/step - loss: 158.0042 - val_loss: 187.0881
Epoch 9/100
23/23 - 0s - 5ms/step - loss: 141.7395 - val_loss: 186.2469
Epoch 10/100
23/23 - 0s - 5ms/step - loss: 128.2609 - val_loss: 213.2476
Epoch 11/100
23/23 - 0s - 5ms/step - loss: 117.5313 - val_loss: 184.9196
Epoch 12/100
23/23 - 0s - 7ms/step - loss: 98.5557 - val_loss: 157.2233
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 88.8457 - val_loss: 168.8580
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 75.9065 - val_loss: 162.9916
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 67.1014 - val_loss: 173.3402
Epoch 16/100
23/23 - 0s - 5ms/step - loss: 61.6384 - val_loss: 185.7835
Epoch 17/100
23/23 - 0s - 5ms/step - loss: 58.6066 - val_loss: 200.4997
Epoch 18/100
23/23 - 0s - 5ms/step - loss: 52.1612 - val_loss: 189.7279
Epoch 19/100
23/23 - 0s - 6ms/step - loss: 48.1679 - val_loss: 161.4461
Epoch 20/100
23/23 - 0s - 5ms/step - loss: 45.3424 - val_loss: 172.2688
Epoch 21/100
23/23 - 0s - 5ms/step - loss: 42.5343 - val_loss: 170.3921
Epoch 22/100
23/23 - 0s - 4ms/step - loss: 41.6802 - val_loss: 140.9488
Epoch 23/100
23/23 - 0s - 4ms/step - loss: 40.3792 - val_loss: 158.4967
Epoch 24/100
23/23 - 0s - 5ms/step - loss: 37.1164 - val_loss: 165.9212
Epoch 25/100
23/23 - 0s - 5ms/step - loss: 35.8839 - val_loss: 176.4359
Epoch 26/100
23/23 - 0s - 5ms/step - loss: 35.3959 - val_loss: 170.2001
Epoch 27/100
23/23 - 0s - 5ms/step - loss: 33.0486 - val_loss: 138.8582
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 31.7057 - val_loss: 150.5065
Epoch 29/100
23/23 - 0s - 5ms/step - loss: 29.7660 - val_loss: 125.0851
Epoch 30/100
23/23 - 0s - 5ms/step - loss: 30.9859 - val_loss: 148.6710
Epoch 31/100
23/23 - 0s - 6ms/step - loss: 27.7317 - val_loss: 132.2791
Epoch 32/100
23/23 - 0s - 6ms/step - loss: 27.0199 - val_loss: 151.0292
Epoch 33/100
23/23 - 0s - 5ms/step - loss: 26.6936 - val_loss: 138.9726
Epoch 34/100
23/23 - 0s - 5ms/step - loss: 25.5921 - val_loss: 139.4446
Epoch 35/100
23/23 - 0s - 5ms/step - loss: 26.4269 - val_loss: 105.1367
Epoch 36/100
23/23 - 0s - 5ms/step - loss: 24.5366 - val_loss: 106.9828
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 24.6243 - val_loss: 125.6477
Epoch 38/100
23/23 - 0s - 7ms/step - loss: 22.8456 - val_loss: 126.1842
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 23.2435 - val_loss: 103.9901
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 22.0821 - val_loss: 117.1813
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 20.5896 - val_loss: 117.8209
Epoch 42/100
23/23 - 0s - 6ms/step - loss: 20.1273 - val_loss: 119.2559
Epoch 43/100
23/23 - 0s - 6ms/step - loss: 20.4046 - val_loss: 115.3694
Epoch 44/100
23/23 - 0s - 5ms/step - loss: 19.8626 - val_loss: 114.8325
Epoch 45/100
23/23 - 0s - 5ms/step - loss: 19.9821 - val_loss: 100.0761
Epoch 46/100
23/23 - 0s - 5ms/step - loss: 19.4284 - val_loss: 100.5300
Epoch 47/100
23/23 - 0s - 8ms/step - loss: 19.2842 - val_loss: 123.1299
Epoch 48/100
23/23 - 0s - 5ms/step - loss: 19.2890 - val_loss: 100.5961
Epoch 49/100
23/23 - 0s - 5ms/step - loss: 18.2326 - val_loss: 113.1742
Epoch 50/100
23/23 - 0s - 5ms/step - loss: 18.4393 - val_loss: 112.3476
Epoch 51/100
23/23 - 0s - 5ms/step - loss: 18.5610 - val_loss: 112.1903
Epoch 52/100
23/23 - 0s - 5ms/step - loss: 17.6363 - val_loss: 107.5766
Epoch 53/100
23/23 - 0s - 5ms/step - loss: 17.2602 - val_loss: 93.9243
Epoch 54/100
23/23 - 0s - 8ms/step - loss: 19.1346 - val_loss: 98.1995
Epoch 55/100
23/23 - 0s - 6ms/step - loss: 16.7773 - val_loss: 81.6247
Epoch 56/100
23/23 - 0s - 6ms/step - loss: 19.3796 - val_loss: 95.0725
Epoch 57/100
23/23 - 0s - 6ms/step - loss: 17.0802 - val_loss: 88.9739
Epoch 58/100
23/23 - 0s - 7ms/step - loss: 16.0580 - val_loss: 105.2567
Epoch 59/100
23/23 - 0s - 8ms/step - loss: 15.5812 - val_loss: 109.3137
Epoch 60/100
23/23 - 0s - 7ms/step - loss: 15.3498 - val_loss: 95.0425
Epoch 61/100
23/23 - 0s - 6ms/step - loss: 15.2861 - val_loss: 117.7802
Epoch 62/100
23/23 - 0s - 7ms/step - loss: 15.0621 - val_loss: 100.3086
Epoch 63/100
23/23 - 0s - 8ms/step - loss: 15.4648 - val_loss: 130.4159
Epoch 64/100
23/23 - 0s - 7ms/step - loss: 15.7242 - val_loss: 122.9578
Epoch 65/100
23/23 - 0s - 7ms/step - loss: 14.8601 - val_loss: 88.8023
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 14.7088 - val_loss: 126.9387
Epoch 67/100
23/23 - 0s - 5ms/step - loss: 15.5154 - val_loss: 104.8451
Epoch 68/100
23/23 - 0s - 5ms/step - loss: 14.7345 - val_loss: 110.2031
Epoch 69/100
23/23 - 0s - 5ms/step - loss: 14.8474 - val_loss: 122.3496
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 13.9693 - val_loss: 101.1604
Epoch 71/100
23/23 - 0s - 6ms/step - loss: 15.0555 - val_loss: 100.4049
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 13.7206 - val_loss: 108.5346
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 13.3232 - val_loss: 110.5591
Epoch 74/100
23/23 - 0s - 6ms/step - loss: 14.2583 - val_loss: 108.0107
Epoch 75/100
23/23 - 0s - 6ms/step - loss: 13.8376 - val_loss: 96.3126
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 13.3657 - val_loss: 105.8027
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 13.8488 - val_loss: 121.1151
Epoch 78/100
23/23 - 0s - 7ms/step - loss: 13.2873 - val_loss: 90.9509
Epoch 79/100
23/23 - 0s - 7ms/step - loss: 14.2872 - val_loss: 126.4179
Epoch 80/100
23/23 - 0s - 7ms/step - loss: 13.4889 - val_loss: 114.6785
Epoch 81/100
23/23 - 0s - 6ms/step - loss: 13.4746 - val_loss: 125.9158
Epoch 82/100
23/23 - 0s - 6ms/step - loss: 12.9525 - val_loss: 123.8174
Epoch 83/100
23/23 - 0s - 7ms/step - loss: 13.7085 - val_loss: 129.1529
Epoch 84/100
23/23 - 0s - 5ms/step - loss: 14.8638 - val_loss: 118.2399
Epoch 85/100
23/23 - 0s - 5ms/step - loss: 13.9690 - val_loss: 116.7582
Epoch 86/100
23/23 - 0s - 5ms/step - loss: 12.4589 - val_loss: 124.9156
Epoch 87/100
23/23 - 0s - 5ms/step - loss: 12.1859 - val_loss: 122.5020
Epoch 88/100
23/23 - 0s - 5ms/step - loss: 12.7028 - val_loss: 125.4826
Epoch 89/100
23/23 - 0s - 4ms/step - loss: 12.3345 - val_loss: 126.7062
Epoch 90/100
23/23 - 0s - 5ms/step - loss: 11.5187 - val_loss: 137.3944
Epoch 91/100
23/23 - 0s - 5ms/step - loss: 11.9251 - val_loss: 137.1239
Epoch 92/100
23/23 - 0s - 5ms/step - loss: 12.5727 - val_loss: 133.8450
Epoch 93/100
23/23 - 0s - 5ms/step - loss: 11.6016 - val_loss: 125.7908
Epoch 94/100
23/23 - 0s - 5ms/step - loss: 12.3452 - val_loss: 134.7204
Epoch 95/100
23/23 - 0s - 5ms/step - loss: 11.4032 - val_loss: 126.7576
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 11.5434 - val_loss: 124.2662
Epoch 97/100
23/23 - 0s - 5ms/step - loss: 11.1157 - val_loss: 151.1999
Epoch 98/100
23/23 - 0s - 5ms/step - loss: 11.5871 - val_loss: 129.0982
Epoch 99/100
23/23 - 0s - 5ms/step - loss: 12.0402 - val_loss: 150.8046
Epoch 100/100
23/23 - 0s - 5ms/step - loss: 11.5392 - val_loss: 143.6022

<h3>Practice Exercise 2</h3>

 Train and evaluate the model simultaneously using the fit() method by reserving 10% of the data for validation and training the model for 100 epochs

In [21]:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 1s - 45ms/step - loss: 1522.4998 - val_loss: 965.8321
Epoch 2/100
29/29 - 0s - 6ms/step - loss: 679.7455 - val_loss: 351.9090
Epoch 3/100
29/29 - 0s - 5ms/step - loss: 254.7061 - val_loss: 228.2099
Epoch 4/100
29/29 - 0s - 5ms/step - loss: 204.3571 - val_loss: 206.4710
Epoch 5/100
29/29 - 0s - 5ms/step - loss: 181.5267 - val_loss: 201.3119
Epoch 6/100
29/29 - 0s - 4ms/step - loss: 167.4855 - val_loss: 175.1256
Epoch 7/100
29/29 - 0s - 4ms/step - loss: 153.6631 - val_loss: 169.5811
Epoch 8/100
29/29 - 0s - 4ms/step - loss: 142.4802 - val_loss: 150.5948
Epoch 9/100
29/29 - 0s - 4ms/step - loss: 128.3510 - val_loss: 123.2548
Epoch 10/100
29/29 - 0s - 4ms/step - loss: 110.3681 - val_loss: 104.1253
Epoch 11/100
29/29 - 0s - 5ms/step - loss: 98.1504 - val_loss: 96.0582
Epoch 12/100
29/29 - 0s - 4ms/step - loss: 84.1362 - val_loss: 88.6385
Epoch 13/100
29/29 - 0s - 4ms/step - loss: 74.5237 - val_loss: 63.5871
Epoch 14/100
29/29 - 0s - 4ms/step - loss: 66.4388 - val_loss: 70.2379
Epoch 15/100
29/29 - 0s - 4ms/step - loss: 60.8922 - val_loss: 59.5601
Epoch 16/100
29/29 - 0s - 11ms/step - loss: 57.1108 - val_loss: 52.9008
Epoch 17/100
29/29 - 0s - 4ms/step - loss: 55.7943 - val_loss: 46.6387
Epoch 18/100
29/29 - 0s - 4ms/step - loss: 49.9447 - val_loss: 39.2306
Epoch 19/100
29/29 - 0s - 4ms/step - loss: 45.7143 - val_loss: 36.4593
Epoch 20/100
29/29 - 0s - 4ms/step - loss: 42.7080 - val_loss: 35.7472
Epoch 21/100
29/29 - 0s - 4ms/step - loss: 40.1062 - val_loss: 32.9613
Epoch 22/100
29/29 - 0s - 4ms/step - loss: 38.4592 - val_loss: 30.6403
Epoch 23/100
29/29 - 0s - 4ms/step - loss: 37.7884 - val_loss: 30.3135
Epoch 24/100
29/29 - 0s - 4ms/step - loss: 34.8289 - val_loss: 28.9647
Epoch 25/100
29/29 - 0s - 4ms/step - loss: 35.0165 - val_loss: 27.4555
Epoch 26/100
29/29 - 0s - 4ms/step - loss: 32.8129 - val_loss: 27.3803
Epoch 27/100
29/29 - 0s - 4ms/step - loss: 33.1361 - val_loss: 29.5068
Epoch 28/100
29/29 - 0s - 5ms/step - loss: 32.5048 - val_loss: 31.8883
Epoch 29/100
29/29 - 0s - 5ms/step - loss: 28.7393 - val_loss: 28.1984
Epoch 30/100
29/29 - 0s - 4ms/step - loss: 28.8189 - val_loss: 28.9503
Epoch 31/100
29/29 - 0s - 4ms/step - loss: 27.8540 - val_loss: 24.5550
Epoch 32/100
29/29 - 0s - 4ms/step - loss: 26.6455 - val_loss: 24.5795
Epoch 33/100
29/29 - 0s - 5ms/step - loss: 25.6892 - val_loss: 34.3493
Epoch 34/100
29/29 - 0s - 4ms/step - loss: 25.9595 - val_loss: 28.1320
Epoch 35/100
29/29 - 0s - 5ms/step - loss: 24.7314 - val_loss: 23.1975
Epoch 36/100
29/29 - 0s - 5ms/step - loss: 25.5738 - val_loss: 24.3146
Epoch 37/100
29/29 - 0s - 4ms/step - loss: 23.3812 - val_loss: 22.7519
Epoch 38/100
29/29 - 0s - 4ms/step - loss: 23.3259 - val_loss: 25.5754
Epoch 39/100
29/29 - 0s - 5ms/step - loss: 22.9302 - val_loss: 22.1037
Epoch 40/100
29/29 - 0s - 6ms/step - loss: 22.3351 - val_loss: 23.3406
Epoch 41/100
29/29 - 0s - 4ms/step - loss: 22.0209 - val_loss: 21.8386
Epoch 42/100
29/29 - 0s - 4ms/step - loss: 21.1028 - val_loss: 25.7229
Epoch 43/100
29/29 - 0s - 4ms/step - loss: 20.6655 - val_loss: 21.5209
Epoch 44/100
29/29 - 0s - 4ms/step - loss: 21.0578 - val_loss: 22.4329
Epoch 45/100
29/29 - 0s - 5ms/step - loss: 20.9761 - val_loss: 23.8938
Epoch 46/100
29/29 - 0s - 5ms/step - loss: 20.2010 - val_loss: 22.2455
Epoch 47/100
29/29 - 0s - 4ms/step - loss: 19.3307 - val_loss: 19.9112
Epoch 48/100
29/29 - 0s - 4ms/step - loss: 19.0829 - val_loss: 25.4963
Epoch 49/100
29/29 - 0s - 4ms/step - loss: 18.9830 - val_loss: 19.3319
Epoch 50/100
29/29 - 0s - 4ms/step - loss: 18.6784 - val_loss: 21.2561
Epoch 51/100
29/29 - 0s - 6ms/step - loss: 18.0900 - val_loss: 22.0263
Epoch 52/100
29/29 - 0s - 6ms/step - loss: 17.7666 - val_loss: 20.1639
Epoch 53/100
29/29 - 0s - 6ms/step - loss: 18.0964 - val_loss: 26.3494
Epoch 54/100
29/29 - 0s - 4ms/step - loss: 17.0947 - val_loss: 21.7851
Epoch 55/100
29/29 - 0s - 4ms/step - loss: 17.8206 - val_loss: 18.7634
Epoch 56/100
29/29 - 0s - 5ms/step - loss: 16.1968 - val_loss: 18.1094
Epoch 57/100
29/29 - 0s - 4ms/step - loss: 18.4283 - val_loss: 19.0185
Epoch 58/100
29/29 - 0s - 4ms/step - loss: 17.9649 - val_loss: 16.0525
Epoch 59/100
29/29 - 0s - 5ms/step - loss: 16.4207 - val_loss: 18.9109
Epoch 60/100
29/29 - 0s - 5ms/step - loss: 15.8012 - val_loss: 16.0782
Epoch 61/100
29/29 - 0s - 7ms/step - loss: 17.3788 - val_loss: 20.8924
Epoch 62/100
29/29 - 0s - 4ms/step - loss: 17.3991 - val_loss: 20.8488
Epoch 63/100
29/29 - 0s - 4ms/step - loss: 16.2919 - val_loss: 20.6989
Epoch 64/100
29/29 - 0s - 4ms/step - loss: 15.5668 - val_loss: 24.7092
Epoch 65/100
29/29 - 0s - 4ms/step - loss: 15.6014 - val_loss: 15.9559
Epoch 66/100
29/29 - 0s - 4ms/step - loss: 14.8165 - val_loss: 15.5474
Epoch 67/100
29/29 - 0s - 4ms/step - loss: 14.9649 - val_loss: 16.6589
Epoch 68/100
29/29 - 0s - 4ms/step - loss: 15.0661 - val_loss: 16.7777
Epoch 69/100
29/29 - 0s - 4ms/step - loss: 14.4336 - val_loss: 14.2099
Epoch 70/100
29/29 - 0s - 4ms/step - loss: 14.8105 - val_loss: 14.2623
Epoch 71/100
29/29 - 0s - 4ms/step - loss: 15.5322 - val_loss: 20.6478
Epoch 72/100
29/29 - 0s - 4ms/step - loss: 16.0345 - val_loss: 17.2777
Epoch 73/100
29/29 - 0s - 4ms/step - loss: 15.7233 - val_loss: 14.9780
Epoch 74/100
29/29 - 0s - 4ms/step - loss: 15.8829 - val_loss: 18.9384
Epoch 75/100
29/29 - 0s - 4ms/step - loss: 14.4365 - val_loss: 16.0979
Epoch 76/100
29/29 - 0s - 4ms/step - loss: 13.6509 - val_loss: 14.2073
Epoch 77/100
29/29 - 0s - 4ms/step - loss: 13.4377 - val_loss: 14.5574
Epoch 78/100
29/29 - 0s - 4ms/step - loss: 12.9707 - val_loss: 26.7100
Epoch 79/100
29/29 - 0s - 4ms/step - loss: 14.0302 - val_loss: 13.2736
Epoch 80/100
29/29 - 0s - 4ms/step - loss: 13.6116 - val_loss: 18.8830
Epoch 81/100
29/29 - 0s - 4ms/step - loss: 14.0383 - val_loss: 15.1384
Epoch 82/100
29/29 - 0s - 4ms/step - loss: 13.6058 - val_loss: 13.3072
Epoch 83/100
29/29 - 0s - 4ms/step - loss: 13.7589 - val_loss: 16.1613
Epoch 84/100
29/29 - 0s - 4ms/step - loss: 13.7840 - val_loss: 13.4603
Epoch 85/100
29/29 - 0s - 4ms/step - loss: 13.5002 - val_loss: 19.6327
Epoch 86/100
29/29 - 0s - 4ms/step - loss: 13.8975 - val_loss: 14.4866
Epoch 87/100
29/29 - 0s - 4ms/step - loss: 13.0319 - val_loss: 14.0058
Epoch 88/100
29/29 - 0s - 4ms/step - loss: 12.8871 - val_loss: 13.4928
Epoch 89/100
29/29 - 0s - 4ms/step - loss: 12.9276 - val_loss: 13.5712
Epoch 90/100
29/29 - 0s - 4ms/step - loss: 11.9039 - val_loss: 13.2200
Epoch 91/100
29/29 - 0s - 4ms/step - loss: 12.5708 - val_loss: 14.6710
Epoch 92/100
29/29 - 0s - 4ms/step - loss: 11.9231 - val_loss: 11.2583
Epoch 93/100
29/29 - 0s - 4ms/step - loss: 12.6379 - val_loss: 11.5718
Epoch 94/100
29/29 - 0s - 4ms/step - loss: 12.5508 - val_loss: 17.3194
Epoch 95/100
29/29 - 0s - 4ms/step - loss: 12.6974 - val_loss: 12.0093
Epoch 96/100
29/29 - 0s - 4ms/step - loss: 15.3448 - val_loss: 25.6588
Epoch 97/100
29/29 - 0s - 4ms/step - loss: 13.4954 - val_loss: 11.6603
Epoch 98/100
29/29 - 0s - 4ms/step - loss: 12.7884 - val_loss: 11.3013
Epoch 99/100
29/29 - 0s - 4ms/step - loss: 11.3028 - val_loss: 10.4850
Epoch 100/100
29/29 - 0s - 4ms/step - loss: 11.9722 - val_loss: 11.8966

Based on the results, we notice that:

- Adding more hidden layers to the model increases its capacity to learn and represent complex relationships within the data. This allows the model to better identify, as a result, the model becomes more effective at fitting the training data and potentially improving its predictions.
- By reducing the proportion of data set aside for validation and using a larger portion for training, the model has access to more examples to learn from. This additional training data helps the model improve its understanding of the underlying trends, which can lead to better overall performance.

Based on the results, we notice that:

- Adding more hidden layers to the model increases its capacity to learn and represent complex relationships within the data. This allows the model to better identify, as a result, the model becomes more effective at fitting the training data and potentially improving its predictions.
- By reducing the proportion of data set aside for validation and using a larger portion for training, the model has access to more examples to learn from. This additional training data helps the model improve its understanding of the underlying trends, which can lead to better overall performance.

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>

## <h3 align="center"> &#169; IBM Corporation. All rights reserved. <h3/>